base_images:
  dev-scripts:
    name: test
    namespace: openshift-kni
    tag: dev-scripts
  openshift_release_golang-1.14:
    name: release
    namespace: openshift
    tag: golang-1.14
  test-infra:
    name: "4.6"
    namespace: ocp
    tag: assisted-test-infra
  ubi8:
    name: ubi
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
- dockerfile_path: Dockerfile.assisted-service
  from: src
  inputs:
    openshift_release_golang-1.14:
      as:
      - registry.svc.ci.openshift.org/openshift/release:golang-1.14
  to: assisted-service
- dockerfile_path: Dockerfile.test-infra
  from: test-infra
  inputs:
    assisted-service:
      as:
      - quay.io/ocpmetal/assisted-service:latest
  to: assisted-test-infra
promotion:
  excluded_images:
  - assisted-test-infra
  name: "4.6"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-metal-assisted
  steps:
    cluster_profile: packet
    post:
    - ref: baremetalds-packet-teardown
    pre:
    - ref: baremetalds-packet-setup
    - ref: ipi-install-rbac
    - ref: baremetalds-assisted-conf-service
    - ref: baremetalds-assisted-setup
zz_generated_metadata:
  branch: master
  org: openshift
  repo: assisted-service
